version: 2
jobs:
  build_frontend_code:
    working_directory: ~/project
    docker:
      - image: node:12-alpine
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
#      - run:
#          name: Build the code
#          command: npm run build
      - store_artifacts:
          path: ~/project
      - persist_to_workspace:
          root: ~/
          paths:
            - project
  build_frontend_container:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - run:
          name: Build the docker image
          command: docker build -t sample:test .
      - attach_workspace:
          at: .
workflows:
  version: 2
  build_frontend:
    jobs:
      - build_frontend_code
      - build_frontend_container