version: 2
jobs:
  build_frontend:
    working_directory: ~/project
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - run:
          name: install packages
          command: npm version && npm install
      - run:
          name: build front-end
          command: npm run build
      - store_artifacts:
          path: ~/project/package
workflows:
  version: 2
  build_frontend:
    jobs:
      - build_frontend
