version: 2.1
jobs:
  build_frontend:
    working_directory: ~/project
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - run:
          name: "Build Front-end"
          command: "npm run build"
      - store_artifacts:
          path: ~/project/package
workflows:
  build_frontend:
    jobs:
      - build_frontend
