version: 2
jobs:
  build_frontend_code:
    working_directory: ~/project
    docker:
      - image: node:12-alpine
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build the code
          command: npm run build
      - store_artifacts:
          path: ~/project
workflows:
  version: 2
  build_frontend:
    jobs:
      - build_frontend_code
