version: 2
jobs:
  build_frontend:
    working_directory: ~/project
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
#      - run:
#          name: Build Frontend
#          command: npm run build
      - store_artifacts:
          path: ~/project/package.json
workflows:
  version: 2
  build_frontend:
    jobs:
      - build_frontend
